version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '12:01'
    commit-message:
      prefix: "[DEPENDABOT]"
    pull-request-branch-name: "dependabot/{package-ecosystem}/{directory}"
    rebase-strategy: "merge-commit"
    labels:
      - dependencies
    reviewers:
      - xdeadboy666x
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: '12:01'
    commit-message:
      prefix: "[DEPENDABOT]"
    pull-request-branch-name: "dependabot/{package-ecosystem}/{directory}"
    rebase-strategy: "merge-commit"
    labels:
      - dependencies
    reviewers:
      - xdeadboy666x
