stages:
  - build

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.pip-cache

default:
  before_script:
    - apt-get update && apt-get install -y sudo
    - sudo ln -sf /usr/share/zoneinfo/America/Mexico_City /etc/localtime
    - sudo dpkg-reconfigure -f noninteractive tzdata
    - sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev git
    - curl https://pyenv.run | bash
    - export PATH="$HOME/.pyenv/bin:$PATH"
    - eval "$(pyenv init --path)"
    - eval "$(pyenv init -)"
    - eval "$(pyenv virtualenv-init -)"
    - pyenv install 3.11.0
    - pyenv global 3.11.0
    - export PATH="$HOME/.pyenv/shims:$PATH"

build:
  stage: build
  image: python:3.11

  script:
    - python --version
    - pip install --cache-dir $PIP_CACHE_DIR -r requirements.txt --no-warn-script-location
    - python main.py

  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - .pip-cache

  only:
    refs:
      - master
    variables:
      - $CI_PIPELINE_SOURCE == "push"
      - $CI_PIPELINE_SOURCE == "merge_request_event"
      - $CI_PIPELINE_SOURCE == "schedule"

  environment:
    name: production
    url: https://gitlab.com/alienchristxv3/FGODLBNA/

  variables:
    userIds: $GAME_USERIDS
    authKeys: $GAME_AUTHKEYS
    secretKeys: $GAME_SECRETKEYS
    fateRegion: $GAME_REGION
    DEVICE_INFO_SECRET: $DEVICE_INFO_SECRET
    USER_AGENT_SECRET_2: $USER_AGENT_SECRET_2
    webhookDiscord: $DISCORD_WEBHOOK