name: FGO Login System

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "00 19,05,15 * * *"
    - cron: "20 22,08 * * *"
    - cron: "40 01,11 * * *"
#    - cron: "15 19,00,05,07,10,12 * * *"
#    - cron: "55 20,08 * * *"
#    - cron: "35 03,15 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Set Time Zone
        run: sudo timedatectl set-timezone 'America/Mexico_City'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        run: pip3 install -r requirements.txt

						 - name: Run main script
        run: python3 main.py && python3 main.py
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          fateRegion: ${{ secrets.GAME_REGION }}
          DEVICE_INFO_SECRET: ${{ secrets.DEVICE_INFO_SECRET }}
          USER_AGENT_SECRET_2: ${{ secrets.USER_AGENT_SECRET_2 }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
