name: FGO Login System

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "00 19 * * *"
    - cron: "20 22 * * *"
    - cron: "40 01 * * *"
    - cron: "00 05 * * *"
    - cron: "20 08 * * *"
    - cron: "40 11 * * *"
    - cron: "00 15 * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set Time Zone
        run: sudo systemsetup -settimezone America/Mexico_City

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install --cache-dir ~/.pip-cache -r requirements.txt --user

      - name: Run main scripts
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          fateRegion: ${{ secrets.GAME_REGION }}
          DEVICE_INFO_SECRET: ${{ secrets.DEVICE_INFO_SECRET }}
          USER_AGENT_SECRET_2: ${{ secrets.USER_AGENT_SECRET_2 }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
