name: FGO Login System NA

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "00 19 * * *"
    - cron: "26 22 * * *"
    - cron: "52 01 * * *"
    - cron: "18 05 * * *"
    - cron: "44 08 * * *"
    - cron: "10 12 * * *"
    - cron: "36 15 * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set Time Zone
        run: sudo systemsetup -settimezone America/Mexico_City

      - uses: actions/checkout@v4
      - name: Checkout data repo
        uses: actions/checkout@v4
      
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip:
          
      - name: Install dependencies
        run: |
          pip install --cache-dir ~/.pip-cache -r requirements.txt --user
          
      - name: Run main scripts
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          fateRegion: ${{ secrets.GAME_REGION }}
          DEVICE_INFO_SECRET: ${{ secrets.DEVICE_INFO_SECRET }}
          USER_AGENT_SECRET_2: ${{ secrets.USER_AGENT_SECRET_2 }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
